on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notify
      uses: actions/checkout@v2
      env:
        SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
      if: always()
      
    - uses: slack/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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 # required
      if: always() # Pick up events even if the job fails or is canceled.
