on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notify
      uses: actions/checkout@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
    - uses: slackapi/slack-github-action@v1.23.0
      with:
        slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        channel-id: '#Testing'
      if: always()
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
