on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "16.x"
    - uses: rtCamp/action-slack-notify@v2
      with:
        status: ${{ job.status }}
        channel-id: B04DQG84X0U
      env:
        SLACK_WEBHOOK:  https://hooks.slack.com/services/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
      if: always()
# On failure
#    - name: Slack Notification - Deployment Failed
#      uses: rtCamp/action-slack-notify@v2
#      if: ${{ failure() }}
#      env:
#        SLACK_COLOR: ${{ job.status }}
#        SLACK_MESSAGE: "Failed deployment :x: commit: ${{ github.event.head_commit.message }}"
#        SLACK_WEBHOOK: https://hooks.slack.com/services/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
