on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    env:
      SLACK_WEBHOOK:  ${{ secrets.WEBHOOK_URL }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code from repo
      uses: actions/checkout@v3

    - name: Slack Notification
      uses: act10ns/slack@1
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel-id: '#general' #B04DQG84X0U
      if: always()
# On failure
#    - name: Slack Notification - Deployment Failed
#      uses: rtCamp/action-slack-notify@v2
#      if: ${{ failure() }}
#      env:
#        SLACK_COLOR: ${{ job.status }}
#        SLACK_MESSAGE: "Failed deployment :x: commit: ${{ github.event.head_commit.message }}"
#        SLACK_WEBHOOK: https://hooks.slack.com/services/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
